export const metadata = {
  metadataBase: new URL("https://saksiam.com"),
  title: {
    default: "นโยบาย | SAKSIAM",
    template: "%s | SAKSIAM",
  },
  description:
    "ศูนย์รวมนโยบาย ประกาศ และเอกสารสำคัญของ บริษัท ศักดิ์สยามลิสซิ่ง จำกัด (มหาชน) เพื่อให้ลูกค้า ผู้ถือหุ้น และผู้มีส่วนได้เสียเข้าถึงข้อมูลได้อย่างถูกต้อง โปร่งใส และเป็นปัจจุบัน",
  keywords: [
    "นโยบาย",
    "นโยบายบริษัท",
    "นโยบายศักดิ์สยาม",
    "นโยบาย SAKSIAM",
    "นโยบาย Saksiam Leasing",
    "ประกาศบริษัท",
    "เอกสารนโยบาย",
    "เอกสารบริษัท",
    "เอกสารสำคัญบริษัท",
    "ข้อกำหนดบริษัท",
    "เงื่อนไขการให้บริการ",
    "ข้อกำหนดและเงื่อนไข",
    "ข้อมูลส่วนบุคคล",
    "คุ้มครองข้อมูลส่วนบุคคล",
    "การคุ้มครองข้อมูลส่วนบุคคล",
    "พระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล",
    "นโยบายคุกกี้",
    "นโยบายการใช้งานคุกกี้",
    "การใช้งานคุกกี้",
    "การจัดการคุกกี้",
    "คุกกี้เว็บไซต์",
    "นโยบายการคุ้มครองข้อมูลส่วนบุคคล",
    "ประกาศความเป็นส่วนตัว",
    "ความเป็นส่วนตัว",
    "ข้อมูลลูกค้า",
    "การเก็บข้อมูลส่วนบุคคล",
    "การใช้ข้อมูลส่วนบุคคล",
    "สิทธิของเจ้าของข้อมูล",
    "สิทธิเจ้าของข้อมูลส่วนบุคคล",
    "การขอใช้สิทธิข้อมูลส่วนบุคคล",
    "การรักษาความปลอดภัยข้อมูล",
    "การเปิดเผยข้อมูลส่วนบุคคล",
    "การประมวลผลข้อมูลส่วนบุคคล",
    "นโยบายการรับเรื่องร้องเรียน",
    "ช่องทางร้องเรียน",
    "ร้องเรียนทุจริต",
    "แจ้งเบาะแส",
    "นโยบายต่อต้านทุจริต",
    "นโยบายการกำกับดูแลกิจการ",
    "นโยบายความยั่งยืน",
    "บรรษัทภิบาล",
    "การกำกับดูแลกิจการ",
    "ความโปร่งใส",
    "ผู้มีส่วนได้เสีย",
    "PDPA",
    "Personal Data Protection Act",
    "Privacy Policy",
    "Cookie Policy",
    "Privacy Notice",
    "Data Protection Policy",
    "Personal Data Protection Policy",
    "Data Subject Rights",
    "Terms and Conditions",
    "Corporate Policy",
    "Company Policy",
    "Whistleblowing Policy",
    "Complaint Policy",
    "Corporate Governance Policy",
    "Sustainability Policy",
    "Saksiam",
    "Saksiam Leasing",
    "SAKSIAM",
    "SAKSIAM policy",
    "Saksiam policy",
    "Saksiam privacy policy",
    "Saksiam cookie policy",
    "Saksiam PDPA",
    "Saksiam personal data protection",
    "บริษัท ศักดิ์สยามลิสซิ่ง จำกัด (มหาชน)",
    "SAKSIAM LEASING PUBLIC COMPANY LIMITED",
  ],
  alternates: {
    canonical: "/policy",
  },
  openGraph: {
    title: "นโยบาย | SAKSIAM",
    description:
      "ศูนย์รวมนโยบาย ประกาศ และเอกสารสำคัญของ บริษัท ศักดิ์สยามลิสซิ่ง จำกัด (มหาชน) เพื่อให้ลูกค้า ผู้ถือหุ้น และผู้มีส่วนได้เสียเข้าถึงข้อมูลได้อย่างถูกต้อง โปร่งใส และเป็นปัจจุบัน",
    url: "https://saksiam.com/policy",
    siteName: "SAKSIAM",
    locale: "th_TH",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "นโยบาย | SAKSIAM",
    description:
      "ศูนย์รวมนโยบาย ประกาศ และเอกสารสำคัญของ บริษัท ศักดิ์สยามลิสซิ่ง จำกัด (มหาชน) เพื่อให้ลูกค้า ผู้ถือหุ้น และผู้มีส่วนได้เสียเข้าถึงข้อมูลได้อย่างถูกต้อง โปร่งใส และเป็นปัจจุบัน",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function PolicyLayout({ children }) {
  return <>{children}</>;
}
